### ISSUE TITLE
ACL 什么时候能支持Acl

### ISSUE THREAD

**Issue by niuniu-blog** [itboon/rocketmq-helm#12]
没有ACL 生产环境没法使用，有什么办法能设置ACL吗？

**Comment by Changego** [comment]
确实呢。我也在等。rocketmq太不活跃了。

**Comment by itboon** [comment]
acl 部署案例：

```yaml
broker:
  aclConfigMapEnabled: true
  config:
    aclEnable: true

  aclConfig: |
    globalWhiteRemoteAddresses:
      - '*'
      - 10.*.*.*
      - 192.168.*.*
```
此处提供的是最小化配置，具体细节请参考官方文档 [RocketMQ 权限控制](https://rocketmq.apache.org/zh/docs/bestPractice/03access)
