### ISSUE TITLE
是否可以让broker被外部访问？

### ISSUE THREAD

**Issue by huangjuyuan** [itboon/rocketmq-helm#13]
现在有一个问题 就是搭建集群后，client端无法在外部进行访问。如果我修改了broker.conf, broker就无法启动了，不知道原因是什么？

**Comment by huangjuyuan** [comment]
Warning  Unhealthy  8s (x2 over 18s)  kubelet            Readiness probe failed: dial tcp 10.234.21.10:10911: connect: connection refused

**Comment by itboon** [comment]
建议你尝试 proxy 解决外部访问

### 集群外访问

可以将 proxy 暴露到集群外，支持 `LoadBalancer` 和 `NodePort`

> proxy 是 RocketMQ 5.x 版本新增的模块，支持 grpc 和 remoting 协议，SDK接入请参考[官方文档](https://rocketmq.apache.org/zh/docs/sdk/01overview)

``` yaml
proxy:
  service:
    annotations: {}
    type: LoadBalancer  ## LoadBalancer or NodePort
```

**Comment by itboon** [comment]
## 通过 proxy 实现集群外访问

可以将 proxy 暴露到集群外，支持 `LoadBalancer` 和 `NodePort`

> proxy 是 RocketMQ 5.x 版本新增的模块，这种模式能够更好的适应复杂的网络环境，尤其是 k8s 集群内外互通，详情请参考[官方文档](https://rocketmq.apache.org/version/#whats-new-in-rocketmq-50)

``` yaml
proxy:
  service:
    annotations: {}
    type: NodePort  ## LoadBalancer or NodePort
```

## hostNetwork

broker 支持 `hostNetwork`，即 pod 使用主机网络命名空间，这种方式的缺点是每个 node 节点最多只能调度一个 broker

``` yaml
broker:
  hostNetwork: true

nameserver:
  service:
    type: NodePort  ## LoadBalancer or NodePort
```

建议优先使用 proxy 实现集群外访问，`hostNetwork` 作为向下兼容的备选方案。

> 仅 broker 支持 `hostNetwork`，其他组件可以使用 `NodePort`
