### ISSUE TITLE
使用helm命令搭建的一些问题

### ISSUE THREAD

**Issue by zhangchaoyanggit** [itboon/rocketmq-helm#19]
版本:5.2.0

**### 1.dashboard服务启动后一直报错**

  INFO Started App in 10.708 seconds (JVM running for 12.017)
2024-06-07T00:56:05.015607197+08:00 [2024-06-06 16:56:05.015] ERROR Unexpected error occurred in scheduled task
java.lang.RuntimeException: java.io.IOException: Read-only file system
2024-06-07T00:56:05.015638754+08:00 	at com.google.common.base.Throwables.propagate(Throwables.java:241)
2024-06-07T00:56:05.015654350+08:00 	at org.apache.rocketmq.dashboard.task.DashboardCollectTask.saveData(DashboardCollectTask.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-06-07T00:56:05.015660552+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-06-07T00:56:05.015663428+08:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
2024-06-07T00:56:05.015668776+08:00 	at 

2.我想本地启动服务的时候连接k8s的rocketmq,默认端口是10911,不是30911 无法开放nodeport端口,我将文件下载下来后修改了rocketmq-cluster broker端口后,broker启动成功 但是一直是 in progress  
 请求博主指导!
<img width="1200" alt="image" src="https://github.com/itboon/rocketmq-helm/assets/24430480/0b9b355e-0dc7-4fde-92f5-41314976aba3">

**Comment by zhangchaoyanggit** [comment]
helm upgrade --install rocketmq \
  --namespace rocketmq \
  --create-namespace \
  rocketmq-repo/rocketmq-cluster

**Comment by itboon** [comment]
不支持 broker 直接使用 nodeport 对外暴露，可用通过 proxy 或者 `--set broker.hostNetwork=true` 解决集群外访问需求。

#### 通过 proxy 实现集群外访问

可以将 proxy 暴露到集群外，支持 `LoadBalancer` 和 `NodePort`

> proxy 是 RocketMQ 5.x 版本新增的模块，这种模式能够更好的适应复杂的网络环境，尤其是 k8s 集群内外互通，详情请参考[官方文档](https://rocketmq.apache.org/version/#whats-new-in-rocketmq-50)

``` yaml
proxy:
  service:
    annotations: {}
    type: NodePort  ## LoadBalancer or NodePort
```

#### hostNetwork

broker 支持 `hostNetwork`，即 pod 使用主机网络命名空间，这种方式的缺点是每个 node 节点最多只能调度一个 broker

``` yaml
broker:
  hostNetwork: true

nameserver:
  service:
    type: NodePort  ## LoadBalancer or NodePort
```
