### ISSUE TITLE
rocketmq5.x自动主从切换没生效

### ISSUE THREAD

**Issue by Yelijah** [itboon/rocketmq-helm#23]
rocketmq5.x自动主从切换需要引入额外的Controller：https://rocketmq.apache.org/zh/docs/deploymentOperations/03autofailover，似乎该chart没有处理。

**Comment by itboon** [comment]
版本 12.3.0 开始支持 controller 主备自动切换模式， 部署案例：

```yaml
controllerModeEnabled: true
controller:
  enabled: true    ## true 表示部署 controller 模块，false 表示将 controller 嵌入 NameServer
broker:
  size:
    master: 1
    replica: 2    ## 必须具有多副本才能进行故障切换，最低 1，建议 2
```

主备自动切换模式与真正的高可用架构不同，故障切换会导致服务有10秒左右不可用

推荐部署多master多slave架构：

```yaml
controllerModeEnabled: false    ## 默认 false
broker:
  size:
    master: 2
    replica: 1
```
