### ISSUE TITLE
values.yaml镜像获取建议添加变量imagePullSecrets

### ISSUE THREAD

**Issue by liuxin638507** [itboon/rocketmq-helm#27]
imagePullSecrets:
        - name: xxx-secret

**Comment by itboon** [comment]
[Chart 12.4.0](https://github.com/itboon/rocketmq-helm/releases/tag/rocketmq-12.4.0) 已支持 imagePullSecrets

```yaml
image:
  repository: "apache/rocketmq"
  tag: "5.3.2"
  pullSecrets:
  - name: secretName
```
