### ISSUE TITLE
账号密码

### ISSUE THREAD

**Issue by sswolf** [itboon/rocketmq-helm#4]
我想咨询一下 账号密码在哪设置  value.yaml没看到相关配置

**Comment by itboon** [comment]
默认不设密码，你可以在 `broker.config` 添加配置试试。

**Comment by aurorasss** [comment]
我想咨询下dashboard如何开启账号密码登陆呢

**Comment by sswolf** [comment]
> 我想咨询下dashboard如何开启账号密码登陆呢

需要自己做镜像

**Comment by Changego** [comment]
没上ACL始终没法玩的。
官方的镜像也是非常的乱。

**Comment by itboon** [comment]
acl 部署案例：

```yaml
broker:
  aclConfigMapEnabled: true
  config:
    aclEnable: true

  aclConfig: |
    globalWhiteRemoteAddresses:
      - '*'
      - 10.*.*.*
      - 192.168.*.*
```
此处提供的是最小化配置，具体细节请参考官方文档 [RocketMQ 权限控制](https://rocketmq.apache.org/zh/docs/bestPractice/03access)
